name: 'Close stale issues'
"on":
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          # Don't process PRs
          days-before-stale: -1

          # Process only issues
          days-before-issue-stale: 60
          days-before-issue-close: 30

          # Add this label after 'days-before-issue-stale' days to mark it as stale
          stale-issue-label: 'no-activity'

          # Process only issues that contain the label 'waiting-for-author'
          only-labels: 'need-more-info'
